// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PourDecisions.Core.Data;

#nullable disable

namespace PourDecisions.Core.Migrations
{
    [DbContext(typeof(CocktailDbContext))]
    [Migration("20260306234901_ChangeIngredientAmountToInt")]
    partial class ChangeIngredientAmountToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PourDecisions.Core.Entities.Bottle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FillLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("Bottles");
                });

            modelBuilder.Entity("PourDecisions.Core.Entities.Cocktail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cocktails");
                });

            modelBuilder.Entity("PourDecisions.Core.Entities.CocktailIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmountUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AmountValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CocktailId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CocktailId");

                    b.HasIndex("TypeId");

                    b.ToTable("CocktailIngredients");
                });

            modelBuilder.Entity("PourDecisions.Core.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("PourDecisions.Core.Entities.IngredientType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IngredientTypes");
                });

            modelBuilder.Entity("PourDecisions.Core.Entities.Bottle", b =>
                {
                    b.HasOne("PourDecisions.Core.Entities.Ingredient", "Ingredient")
                        .WithMany("Bottles")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("PourDecisions.Core.Entities.CocktailIngredient", b =>
                {
                    b.HasOne("PourDecisions.Core.Entities.Cocktail", "Cocktail")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PourDecisions.Core.Entities.IngredientType", "Type")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cocktail");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PourDecisions.Core.Entities.Ingredient", b =>
                {
                    b.HasOne("PourDecisions.Core.Entities.IngredientType", "Type")
                        .WithMany("Ingredients")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PourDecisions.Core.Entities.Cocktail", b =>
                {
                    b.Navigation("CocktailIngredients");
                });

            modelBuilder.Entity("PourDecisions.Core.Entities.Ingredient", b =>
                {
                    b.Navigation("Bottles");
                });

            modelBuilder.Entity("PourDecisions.Core.Entities.IngredientType", b =>
                {
                    b.Navigation("CocktailIngredients");

                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
